apiVersion: v2
name: mission-control
description: K3s Mission Control dashboard — a Kubernetes-deployed Node.js app 
type: application

# version: the chart version — increment this when you change templates or values 
version: 1.2.1

# appVersion: the version of the application being deployed - Increment this when you change app code or update the base image
appVersion: "5.0.0"

keywords:
- nodejs
- kubernetes
- dashboard

maintainers:
  - name: Tonyb23 
    email: ubanianthony23@email.com