name: Build and Deploy to K3s

# Trigger: run this workflow on every push to main 
on:
    push:
      branches:
      - main
permissions:
  contents: read
  packages: write
  
env:
    IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/k3s-mission-control 

jobs:
    # ── JOB 1: Build the image and push to Docker Hub ────────── 
    build-and-push:
        name: Build Docker Image 
        runs-on: ubuntu-latest 
        steps:

            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build Docker image
              run: |
                docker build -t ${{ env.IMAGE_NAME }}:latest .
                docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:${{ github.sha }}

            - name: Push to Docker Hub
              run: |
                docker push ${{ env.IMAGE_NAME }}:latest
                docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}

    # ── JOB 2: Deploy to K3s on EC2 ──────────────────────────── 
    deploy:
        name: Deploy with Helm
        runs-on: ubuntu-latest
        needs: build-and-push	# Only runs after Job 1 succeeds 
        steps:

            - name: Checkout code
              uses: actions/checkout@v4

            # Install kubectl
            - name: Set up kubectl
              uses: azure/setup-kubectl@v3
            
            # Install Helm
            - name: Set up Helm
              uses: azure/setup-helm@v4

            # Write kubeconfig so kubectl and Helm can reach K3s on EC2
            - name: Configure kubeconfig 
              run: |
                mkdir -p $HOME/.kube
                echo "${{ secrets.KUBECONFIG_DATA }}" > $HOME/.kube/config 
                chmod 600 $HOME/.kube/config

            # Deploy using Helm — one command replaces all kubectl apply calls 
            # --install : install if not exists, upgrade if it does 
            # --wait : wait until all pods are Running before succeeding 
            # --timeout : fail if rollout takes longer than 3 minutes
            - name: Deploy with Helm 
              run: |
                helm upgrade --install mission-control ./mission-control \
                  --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/k3s-mission-control \
                  --set image.tag=${{ github.sha }} \
                  --set config.version="${{ github.sha }}" \
                  --set secrets.apiKey="${{ secrets.API_KEY }}" \
                  --wait \
                  --timeout 3m
            
            - name: Package and push chart to GHCR
              run: |
                helm package ./mission-control
                echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io \
                  --username ${{ github.actor }} \
                  --password-stdin
                helm push mission-control-*.tgz oci://ghcr.io/tonyb23/helm-charts  

            #Print release info after deploy
            - name: Show Release status
              run: |
                helm list
                helm status mission-control
                kubectl get pods -l app.kubernetes.io/instance=mission-control